In [ ]:
!pip install langgraph
!pip install langchain-groq
!pip install langchain langchain_core langchain_community fastembed

Requirement already satisfied: langgraph in /usr/local/lib/python3.12/dist-packages (1.1.9)
Requirement already satisfied: langchain-core<2,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph) (1.3.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph) (4.0.2)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.9 in /usr/local/lib/python3.12/dist-packages (from langgraph) (1.0.10)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph) (0.3.13)
Requirement already satisfied: pydantic>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langgraph) (2.12.3)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph) (3.6.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2,>=1.3.0->langgraph) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2,>=1.3.0->langgraph) (0.7.34)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2,>=1.3.0->langgraph) (26.1)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2,>=1.3.0->langgraph) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2,>=1.3.0->langgraph) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2,>=1.3.0->langgraph) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2,>=1.3.0->langgraph) (0.14.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph) (1.12.2)
Requirement already satisfied: httpx>=0.25.2 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph) (0.28.1)
Requirement already satisfied: orjson>=3.11.5 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph) (3.11.8)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.7.4->langgraph) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.7.4->langgraph) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.7.4->langgraph) (0.4.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2,>=1.3.0->langgraph) (3.1.1)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2,>=1.3.0->langgraph) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2,>=1.3.0->langgraph) (2.32.4)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2,>=1.3.0->langgraph) (0.25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2,>=1.3.0->langgraph) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2,>=1.3.0->langgraph) (2.5.0)
Collecting langchain-groq
  Downloading langchain_groq-1.1.2-py3-none-any.whl.metadata (2.4 kB)
Collecting groq<1.0.0,>=0.30.0 (from langchain-groq)
  Downloading groq-0.37.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.8 in /usr/local/lib/python3.12/dist-packages (from langchain-groq) (1.3.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.12/dist-packages (from groq<1.0.0,>=0.30.0->langchain-groq) (4.15.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.8->langchain-groq) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.8->langchain-groq) (0.7.34)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.8->langchain-groq) (26.1)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.8->langchain-groq) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.8->langchain-groq) (9.1.4)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.8->langchain-groq) (0.14.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq<1.0.0,>=0.30.0->langchain-groq) (3.13)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.8->langchain-groq) (3.1.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain-groq) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain-groq) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain-groq) (2.32.4)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain-groq) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain-groq) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq<1.0.0,>=0.30.0->langchain-groq) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain-groq) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.8->langchain-groq) (2.5.0)
Downloading langchain_groq-1.1.2-py3-none-any.whl (19 kB)
Downloading groq-0.37.1-py3-none-any.whl (137 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.5/137.5 kB 4.5 MB/s eta 0:00:00
Installing collected packages: groq, langchain-groq
Successfully installed groq-0.37.1 langchain-groq-1.1.2
Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.15)
Requirement already satisfied: langchain_core in /usr/local/lib/python3.12/dist-packages (1.3.1)
Collecting langchain_community
  Downloading langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)
Collecting fastembed
  Downloading fastembed-0.8.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: langgraph<1.2.0,>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.1.9)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain_core) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain_core) (0.7.34)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain_core) (26.1)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain_core) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain_core) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain_core) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain_core) (0.14.1)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (3.13.5)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (0.4.3)
Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain_community)
  Downloading langchain_classic-1.0.7-py3-none-any.whl.metadata (5.1 kB)
Collecting langchain_core
  Downloading langchain_core-1.4.0-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.0.2)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.14.0)
Collecting requests<3.0.0,>=2.32.5 (from langchain_community)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain_community) (2.0.49)
Collecting langchain-protocol>=0.0.14 (from langchain_core)
  Downloading langchain_protocol-0.0.15-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: huggingface-hub<2.0,>=0.20 in /usr/local/lib/python3.12/dist-packages (from fastembed) (1.11.0)
Collecting loguru<0.8.0,>=0.7.2 (from fastembed)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: mmh3<6.0.0,>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from fastembed) (5.2.1)
Collecting onnxruntime!=1.20.0,!=1.24.0,!=1.24.1,>=1.17.0 (from fastembed)
  Downloading onnxruntime-1.26.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Requirement already satisfied: pillow<13.0,>=10.3.0 in /usr/local/lib/python3.12/dist-packages (from fastembed) (11.3.0)
Collecting py-rust-stemmers<0.2.0,>=0.1.0 (from fastembed)
  Downloading py_rust_stemmers-0.1.8-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Requirement already satisfied: tokenizers<1.0,>=0.15 in /usr/local/lib/python3.12/dist-packages (from fastembed) (0.22.2)
Requirement already satisfied: tqdm<5.0,>=4.66 in /usr/local/lib/python3.12/dist-packages (from fastembed) (4.67.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain_community) (1.23.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.20->fastembed) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.20->fastembed) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.20->fastembed) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.20->fastembed) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.20->fastembed) (0.24.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain_core) (3.1.1)
Collecting langchain-text-splitters<2.0.0,>=1.1.2 (from langchain-classic<2.0.0,>=1.0.7->langchain_community)
  Downloading langchain_text_splitters-1.1.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (4.0.2)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.9 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (1.0.10)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (0.3.13)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (3.6.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain_core) (3.11.8)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain_core) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain_core) (0.25.0)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime!=1.20.0,!=1.24.0,!=1.24.1,>=1.17.0->fastembed) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime!=1.20.0,!=1.24.0,!=1.24.1,>=1.17.0->fastembed) (5.29.6)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain_community) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain_community) (2026.4.22)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain_community) (3.4.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=0.20->fastembed) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=0.20->fastembed) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=0.20->fastembed) (0.16.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.5->langchain) (1.12.2)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.20->fastembed) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.20->fastembed) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.20->fastembed) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=0.20->fastembed) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.20->fastembed) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.20->fastembed) (2.20.0)

In [ ]:
import requests
import json
import pandas as pd
from groq import Groq
import re

# -----------------------------
# 1. INIT LLM CLIENT
# -----------------------------
client = Groq(api_key="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")

# -----------------------------
# 2. EBAY API CALL
# -----------------------------
token = "v^1.1#i^1#p^3#I^3#r^0#f^0#t^H4sIAAAAAAAA/+Vaa2xbVx2P82jVbS3TBjSqJmS87Uuja9+H77V9iY2cxknc5mmnaRvYsnPPPdc+zX1495ybxNFU0qBGGtOmthoIBNPKh1WV4MMQ7APbOrFWKmiso+IhdWiIhVYaErAhmISENsa5TuK6gbZxXJgR94t9zvm/fv/z///P415+Ycu23UsDS3/bHtjaemqBX2gNBIQ7+W1bOrp2tLXu6mjhawgCpxYeWGhfbPt9NwGWWVJziJQcm6DgnGXaRK10JkOea6sOIJioNrAQUSlU8+mhQVUM82rJdagDHTMUzPYmQzLUeUFEksjzKB6TdNZrr8kcd5IhUVB4RZOkuBaFIhANNk6Ih7I2ocCmbJwXFY6XOVEaF0RVjqo8H07EpclQcAK5BDs2IwnzoVTFXLXC69bYenNTASHIpUxIKJVN9+VH0tnezPB4d6RGVmrVD3kKqEeub+1xdBScAKaHbq6GVKjVvAchIiQUSa1ouF6oml4zZhPmV1wdVaCWMPioEoeanJBit8WVfY5rAXpzO/werHNGhVRFNsW0fCuPMm9ohxGkq61hJiLbG/R/xjxgYgMjNxnK9KQP7c9ncqFgfnTUdWawjnQfqRiPxuNRKSbKoRS2OFmJiqsqVuSsOnidjj2OrWPfXSQ47NAexOxF670SrfEKIxqxR9y0QX1baumia96LRSf96VyZP48WbX9GkcVcEKw0b+37tWC4Nv23Kxx0OcZiQdcEBKKyrMg3CAc/1+sKiZQ/K+nR0YhvC9JAmbOAO41oyQQQcZC517OQi3VVkg1RihuI05WEwUUThsFpsq5wgoEQj5CmwUT8/yMyKHWx5lFUjY71AxV4yVAeOiU06pgYlkPrSSp1ZjUW5kgyVKS0pEYis7Oz4Vkp7LiFCCuxQuTg0GAeFpEFQlVafGtiDleiAiLGRbBKyyVmzRwLOqbcLoRSkquPApeW88g0WcdayF5nW2p97w1A7jEx88A4U9FcGAccQpHeEDQdzWCIprDeXMhEMR6XYnFF9HM9wfNiQyBNp4DtIUSLTpPB7B8Z6R/MNISNlU9AmwtVTXXh5bUqJEkcH2P/GgKbLpWyluVRoJko22RzKcf5mJJoCF7J85otEWdFaJdn0Bw1SUPQ/FVXxcBQqTON7H9fSv1c/zix5jJ9uUx+YGp8ZF9muCG0OWS4iBTHfazNFqfpsfRgmj1D/TGnOHZYAdH+WI+ecw7PjJmH+vZqpPToxFiP7LhQmssOKHMo3aOMFQ72R3omRgWcGDkoI9grztj708lkQ07KI+iiJitdfUZ+RN8LvMOT2YlYD+rar/WPEsXtnRwe6DJpYV9aOwSFKO0x42ONgR8qNFumV5fchpfb8RuneBWgn+sfA0h3JTGnKlVoirUaApopNF29RnFFEeUEEhI6DxQxJsR5IInsIMMePaErDS+/TYY3awFg54uMzv/DjeZ6OQ2guA6hbnCiwFwgS1qDi3KzzfHtWpOJf3b7L0Dzc70OeL4MwoSAEg7724YwdKyIAzxa9LumKlYHN0IUIezsF1456jPJYRcB3bHN8maY6+DB9gw7LTpueTMKq8x18AAIHc+mm1G3yloHh+GZBjZN/0pgMwpr2Osx0wZmmWJINqUS2360kTpYSqBcAahjUvLzZUOcrM9CLkRhrK9cKG7GWBcxhaByibYZpjpVVk22HYoNDFdkEE8j0MWljVtxTY6f6zeStRl/EJYLdU3dCsOGVNVwIR2ZeAZtNO2qeBmLs6nSYIFSacNlparOQoSAQr3xaCCkawBO18lGirhiY2P3S46FITab7OKst8E7F6RjF0E65bm4uYBVtkNTbD9UxDq3bm/EATT/KGbh0xB2P1pWr9L8XG8u9L234ezei2aabZMbldjZTNQhBw1B56JRLcFpkgi5WCIBhURMERQoNIS56a4QhVgsIUf5uNTYhVoOAdNqLmQl19E96C+H/1PI2o8e/4+AW9dR87rpX94xRq5/vZ9qqTzCYuAcvxh4pTUQ4Lv5B4X7+c9uadvf3nbXLoIp24sBI0xwwQbUc1F4GpVLALut97a89qs3hz/z0t4zj1/duXDsgcjJlh01XxeceojvrH5fsK1NuLPmYwP+vmsjHcIndm4XFV4WJUFk4cpP8vdfG20XPt3+SXpgede5r4FfHntWeMM68/iSePl0J7+9ShQIdLS0LwZaJh87luxqf/pzb3+v46TQ2Ro8svUHhcJTr89dmnzxD5b60F8WX0x967l7ls9dfIsMLr9wqOtLdOsd08cf+fE9ub6OILy7/83L9118WPnCO689ta9d/+EHJ379xDsf/ukF9XdnXj82P/H87k7zu18+svjBpece+433lct9sZ3vwp++f/LkdxZP7zieXkq/tTXZdteej96/euXlbyxfevLhnyu5+N+j5xfOfv7K/M86X33vjsK9r/71w/Yjfzaf7L6Qn+958ITuXHlGeK+87RH+t1+84NLQt5Wz//hq4eJS5uwrU5964keFl//4zTdaD0SePzF99KMLp7sXTxzYvfyLC87X+17iMs8Gz/8k8O7bxaHwmauXj35//nx4enJlLv8Jb1yJEvchAAA="
url = "https://api.ebay.com/buy/browse/v1/item_summary/search"

headers = {
    "Authorization": f"Bearer {token}",
    "X-EBAY-C-MARKETPLACE-ID": "EBAY_US"
}

params = {
    "q": ["Rolex 2030 4429","Rolex 1570 7831","Rolex 3030 5309", "Rolex 4030 502", "Rolex 4030 311", "Tudor 390 260"]
    #"limit": 20
}

response = requests.get(url, headers=headers, params=params)
data = response.json()

listings = data.get("itemSummaries", [])


# -----------------------------
# 3. GET ITEM DETAILS
# -----------------------------
def get_item_details(item_id):
    url = f"https://api.ebay.com/buy/browse/v1/item/{item_id}"
    r = requests.get(url, headers=headers)
    return r.json() if r.status_code == 200 else {}


#build full dataset (IMPORTANT: multiple rows)
final_data = []

for item in listings:
    item_id = item.get("itemId")
    if item_id:
        final_data.append(get_item_details(item_id))


# -----------------------------
# 4. LLM EXTRACTION
# -----------------------------
def extract_with_llm(title,condition):

    # -----------------------------
    # RULE-BASED EXTRACTION FIRST
    # -----------------------------

    title_lower = title.lower()
    condition = condition.lower()

    # brand
    brand = "Rolex" if "rolex" in title_lower else None

    # component type
    components = [
        "escape wheel",
        "balance wheel",
        "third wheel",
        "rotor",
        "stem",
        "barrel",
        "barrel arbor",
        "mainspring"
    ]

    component_type = None
    for comp in components:
        if comp in title_lower:
            component_type = comp
            break

    # #condition
    if condition in ("new with tags", "new without tags"):
        condition = "New"
    elif condition in ("pre-owned"):
        condition = "Used"
    elif condition in ("refurbished"):
        condition = "Refurbished"
    else:
      condition = None

    # -----------------------------
    # NUMERIC EXTRACTION
    # -----------------------------

    numbers = re.findall(r'\d+', title)

    calibers = []
    part_numbers = []

    for num in numbers:
        if len(num) == 4:
            n = int(num)

            # Rolex calibers usually lower range
            if 1000 <= n <= 3999:
                calibers.append(num)

            # Part numbers usually higher
            if 4000 <= n <= 9999:
                part_numbers.append(num)

    caliber = calibers[0] if calibers else None
    part_number = part_numbers[0] if part_numbers else None

    # -----------------------------
    # FALLBACK TO LLM ONLY IF MISSING
    # -----------------------------

    if brand and caliber and part_number and component_type:
        return {
            "brand": brand,
            "caliber": caliber,
            "part_number": part_number,
            "condition": condition,
            "component_type": component_type
        }

    prompt = f"""
    Extract:

    brand
    caliber
    part_number
    condition
    component_type

    Return only JSON.

    Title:
    {title}
    """

    try:
        completion = client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "user", "content": prompt}
            ]
        )

        output = completion.choices[0].message.content
        llm_result = json.loads(output)

        return {
            "brand": brand or llm_result.get("brand"),
            "caliber": caliber or llm_result.get("caliber"),
            "part_number": part_number or llm_result.get("part_number"),
            "condition": condition or llm_result.get("condition"),
            "component_type": component_type or llm_result.get("component_type")
        }

    except:
        return {
            "brand": brand,
            "caliber": caliber,
            "part_number": part_number,
            "condition": condition,
            "component_type": component_type
        }


# -----------------------------
# 5. PIPELINE
# -----------------------------
def extract_ebay_data(final_data):

    rows = []

    for item in final_data:

        title = item.get("title")
        condition = item.get("condition")

        #price
        price = item.get("price", {})
        price_value = float(price.get("value", 0)) if price.get("value") else 0
        currency = price.get("currency")

        #shipping
        shipping_options = item.get("shippingOptions", [])
        shipping_costs = []

        for s in shipping_options:
            cost = s.get("shippingCost", {}).get("value")
            if cost:
                shipping_costs.append(float(cost))

        shipping_cost = min(shipping_costs) if shipping_costs else 0
        net_price = price_value + shipping_cost

        #seller
        seller = item.get("seller", {})
        seller_score = seller.get("feedbackScore")
        seller_pct = seller.get("feedbackPercentage")

        #availability
        availability = item.get("estimatedAvailabilities", [{}])[0]
        sold_qty = availability.get("estimatedSoldQuantity")
        remaining_qty = availability.get("estimatedRemainingQuantity")

        #location
        location = item.get("itemLocation", {})
        country = location.get("country")

        #time
        created = item.get("itemCreationDate")

        # ---------------- LLM ----------------
        extracted = extract_with_llm(title or "", condition)

        #synthetic id
        synthetic_id = "_".join([
            extracted.get("brand") or "UNK",
            extracted.get("caliber") or "UNK",
            extracted.get("part_number") or "UNK",
            extracted.get("condition") or "UNK",
            extracted.get("component_type") or "UNK"
        ])

        ##final append of data
        rows.append({
            "item_id": item.get("itemId"),
            "title": title,

            "price": price_value,
            "shipping_cost": shipping_cost,
            "net_price": net_price,

            "currency": currency,

            "brand": extracted.get("brand"),
            "caliber": extracted.get("caliber"),
            "part_number": extracted.get("part_number"),
            "condition": extracted.get("condition"),
            "component_type": extracted.get("component_type"),

            "synthetic_id": synthetic_id,

            "seller_score": seller_score,
            "seller_feedback_pct": seller_pct,

            "sold_qty": sold_qty,
            "remaining_qty": remaining_qty,

            "country": country,
            "created_at": created
        })

    return pd.DataFrame(rows)


# -----------------------------
# 6. MAIN
# -----------------------------
df = extract_ebay_data(final_data)

df.to_csv("watch_dataset.csv", index=False)

df

,item_id,title,price,shipping_cost,net_price,currency,brand,caliber,part_number,condition,component_type,synthetic_id,seller_score,seller_feedback_pct,sold_qty,remaining_qty,country,created_at
0,v1|256447115234|556586004259,Genuine ROLEX 2030 Watch Parts 4421 4422 4427 ...,35.00,0.00,35.00,USD,Rolex,2030,4421,New,None,Rolex_2030_4421_New_UNK,1809,99.3,1,1,US,2024-03-15T17:56:52.000Z
1,v1|263029195134|0,Brand New Factory Rolex Part Cal. 2030-4429 Es...,142.73,0.00,142.73,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,954,100.0,2,2,US,2017-06-09T19:35:55.000Z
2,v1|227210898869|0,Rolex 2030 4429 Used Good Condition Escape Wheel,102.71,55.00,157.71,USD,Rolex,2030,4429,Used,escape wheel,Rolex_2030_4429_Used_escape wheel,1330,100.0,0,5,IT,2026-02-10T05:58:06.000Z
3,v1|226902735709|0,Rolex 2030 4432 Used Good Condition Balance Wheel,385.17,55.00,440.17,USD,Rolex,2030,4432,Used,balance wheel,Rolex_2030_4432_Used_balance wheel,1330,100.0,8,4,IT,2025-08-04T09:22:31.000Z
4,v1|178028834648|0,Brand New Factory Rolex Part Cal. 2030-4429 Es...,120.00,0.00,120.00,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,6107,99.7,1,5,US,2026-04-07T00:48:57.000Z
5,v1|176571429477|0,Genuine Rolex 2030 2035 4429 Escape Wheel,95.00,5.00,100.00,USD,Rolex,2030,4429,Used,escape wheel,Rolex_2030_4429_Used_escape wheel,355,100.0,7,2,US,2024-09-12T01:10:55.000Z
6,v1|306354920959|0,ROLEX-ESCAPE WHEEL-FACTORY SEALED-CAL 2030 PAR...,108.00,0.00,108.00,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,1655,99.7,2,2,US,2025-06-16T19:29:32.000Z
7,v1|306049913094|0,"Rolex Original New 2030 2035, 4429 Escape Whee...",73.88,40.30,114.18,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,617,100.0,5,21,GB,2025-01-18T21:50:56.000Z
8,v1|306752648885|0,"Rolex Original New 2030 2035, 4429 Escape Whee...",76.95,40.25,117.20,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,617,100.0,2,21,GB,2026-02-05T21:34:18.000Z
9,v1|176227155632|0,Rolex 2030 2035 watch movement part escape whe...,100.00,12.00,112.00,USD,Rolex,2030,4429,Used,escape wheel,Rolex_2030_4429_Used_escape wheel,35159,100.0,0,1,US,2024-02-07T00:06:06.000Z
10,v1|226425174320|0,Genuine Rolex 2035 2030-4429 Escape Wheel - Ne...,175.00,0.00,175.00,USD,Rolex,2035,4429,New,escape wheel,Rolex_2035_4429_New_escape wheel,3603,99.8,4,2,US,2024-10-30T22:13:44.000Z
11,v1|176571398474|0,Genuine Rolex 2030 2035 4425 Third Wheel,28.00,7.99,35.99,USD,Rolex,2030,4425,Used,third wheel,Rolex_2030_4425_Used_third wheel,355,100.0,14,41,US,2024-09-12T00:49:24.000Z
12,v1|187840407423|0,ONE NEW Sealed Original Rolex part 2030-4429 E...,99.00,20.00,119.00,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,349,99.7,0,6,AE,2025-12-14T08:55:08.000Z
13,v1|227185022459|0,Rolex 2030 4429 New Blister X1 Piece Escape Wheel,186.79,55.00,241.79,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,1330,100.0,0,3,IT,2026-01-22T21:28:21.000Z
14,v1|134441261075|0,Rolex 2030-4474 Rotor. Sealed. Genuine New Old...,79.99,3.00,82.99,USD,Rolex,2030,4474,New,rotor,Rolex_2030_4474_New_rotor,21911,100.0,7,2,US,2023-02-07T20:35:38.000Z
15,v1|147174301174|0,Genuine Rolex 2030 4421 barrel arbor NEW/SEALE...,80.00,6.00,86.00,USD,Rolex,2030,4421,New,barrel,Rolex_2030_4421_New_barrel,14027,99.9,0,1,US,2026-02-26T20:45:12.000Z
16,v1|358370765683|0,Genuine Rolex Escape Wheel Cal 2030/2035 Ladie...,175.00,10.00,185.00,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,3577,100.0,0,2,US,2026-03-24T19:50:29.000Z
17,v1|146502574903|0,original Rolex 2030 4425 Third Wheel NEW/NOS/F...,65.00,6.00,71.00,USD,Rolex,2030,4425,New,third wheel,Rolex_2030_4425_New_third wheel,14027,99.9,3,1,US,2025-04-07T16:52:29.000Z
18,v1|196347170945|496241276938,Rolex 2030/35 New & Pre-owned parts. See drop ...,38.00,0.00,38.00,USD,Rolex,2030,None,Used,None,Rolex_2030_UNK_Used_UNK,775,100.0,0,1,US,2024-04-15T19:01:55.000Z
19,v1|117102283091|0,BRAND NEW FACTORY SEALED Rolex 2030-4440 Slidi...,50.00,6.00,56.00,USD,Rolex,2030,4440,New,None,Rolex_2030_4440_New_UNK,3104,99.9,0,1,US,2026-03-22T21:25:55.000Z
20,v1|223936421095|0,Genuine Rolex 2030 4422 Barrel Complete With M...,185.00,0.00,185.00,USD,Rolex,2030,4422,New,barrel,Rolex_2030_4422_New_barrel,3603,99.8,9,2,US,2020-03-04T18:52:53.000Z
21,v1|176571324550|0,Genuine Rolex 2030 2035 4442 Great Wheel,28.00,7.99,35.99,USD,Rolex,2030,4442,Used,None,Rolex_2030_4442_Used_UNK,355,100.0,10,15,US,2024-09-12T00:05:13.000Z
22,v1|134955142167|0,original Rolex 2030 4425 Third Wheel Genuine N...,40.00,5.15,45.15,USD,Rolex,2030,4425,New,third wheel,Rolex_2030_4425_New_third wheel,14027,99.9,1,8,US,2024-02-27T23:34:18.000Z
23,v1|224137333707|0,Genuine Rolex 2035 2030-4425 Third Wheel - New...,69.95,0.00,69.95,USD,Rolex,2035,4425,New,third wheel,Rolex_2035_4425_New_third wheel,3603,99.8,2,1,US,2020-08-28T22:59:40.000Z
24,v1|144935048803|0,Rolex 2030 4454 Intermediate Setting Wheel. Ge...,26.37,3.00,29.37,USD,Rolex,2030,4454,New,None,Rolex_2030_4454_New_UNK,21911,100.0,14,5,US,2023-02-07T20:35:38.000Z
25,v1|157711501371|0,GENUINE Authentic Rolex 2030 2035 4422 315 Bar...,120.00,6.00,126.00,USD,Rolex,2030,4422,New,barrel,Rolex_2030_4422_New_barrel,3104,99.9,0,1,US,2026-02-26T23:07:16.000Z
26,v1|156094103816|0,"Rolex Second Wheel ,Cal 2030 - 4426, New Old...",65.00,7.00,72.00,USD,Rolex,2030,4426,New,None,Rolex_2030_4426_New_UNK,3005,100.0,0,2,US,2024-03-02T19:13:39.000Z
27,v1|144935048787|0,Rolex 2030 4458 Hour Wheel. Sealed. Genuine Ne...,58.00,3.00,61.00,USD,Rolex,2030,4458,New,Hour Wheel,Rolex_2030_4458_New_Hour Wheel,21911,100.0,1,9,US,2023-02-07T20:35:38.000Z
28,v1|376090184590|0,Genuine Rolex 2030-4429 Escape Wheel Factory S...,137.50,11.03,148.53,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,47,100.0,0,1,CA,2025-03-22T17:16:48.000Z
29,v1|227196706893|0,Rolex 2030 4422 New Blister X1 Piece Barrel wi...,191.94,55.00,246.94,USD,Rolex,2030,4422,New,barrel,Rolex_2030_4422_New_barrel,1330,100.0,0,1,IT,2026-01-31T14:24:36.000Z
30,v1|134441261095|0,Rolex 2030 4493 Cap Jewel. Factory Sealed. Gen...,23.99,3.00,26.99,USD,Rolex,2030,4493,New,None,Rolex_2030_4493_New_UNK,21911,100.0,4,30,US,2023-02-07T20:35:38.000Z
31,v1|227219965784|0,Rolex 2030 4490 New Blister X1 Piece Shock Abs...,127.53,55.00,182.53,USD,Rolex,2030,4490,New,None,Rolex_2030_4490_New_UNK,1330,100.0,1,1,IT,2026-02-16T21:11:23.000Z
32,v1|277814793508|0,GENUINE Rolex 2030 2035 4472 Automatic Device ...,78.00,0.00,78.00,USD,Rolex,2030,4472,Used,None,Rolex_2030_4472_Used_UNK,3692,100.0,1,1,US,2026-03-18T17:46:11.000Z
33,v1|117186722738|0,original Rolex 2030 4424 GREAT WHEEL - NEW OLD...,80.00,6.00,86.00,USD,Rolex,2030,4424,New,None,Rolex_2030_4424_New_UNK,3104,99.9,0,1,US,2026-05-09T16:44:42.000Z
34,v1|226425142711|0,Genuine Rolex 2035 2030-4424 Great Wheel - New...,85.00,0.00,85.00,USD,Rolex,2035,4424,New,None,Rolex_2035_4424_New_UNK,3603,99.8,3,2,US,2024-10-30T21:36:48.000Z
35,v1|157089309455|0,Rolex Cal. 2030 4426 Fourth Wheel - New in s...,49.99,0.00,49.99,USD,Rolex,2030,4426,New,None,Rolex_2030_4426_New_UNK,326,100.0,0,1,US,2025-06-12T13:25:43.000Z
36,v1|224091632608|0,Rolex 2030-4425 2035 Third Wheel New Genuine R...,43.20,0.00,43.20,USD,Rolex,2030,4425,New,third wheel,Rolex_2030_4425_New_third wheel,3603,99.8,4,3,US,2020-07-23T23:58:12.000Z
37,v1|275627283149|0,GENUINE Rolex 2030 2035 4474 Oscillating Wei...,90.00,0.00,90.00,USD,Rolex,2030,4474,Used,None,Rolex_2030_4474_Used_UNK,3692,100.0,5,6,US,2023-01-16T17:31:00.000Z
38,v1|144935048784|0,Rolex 2030 4438 Stem. Price is for one stem. G...,19.99,3.00,22.99,USD,Rolex,2030,4438,New,stem,Rolex_2030_4438_New_stem,21911,100.0,5,12,US,2023-02-07T20:35:38.000Z
39,v1|144376334408|0,GENUINE ROLEX 2030 - 2035 4474 OSCILLATING WEI...,185.00,11.50,196.50,USD,Rolex,2030,4474,Used,rotor,Rolex_2030_4474_Used_rotor,14027,99.9,2,2,US,2022-01-18T18:26:13.000Z
40,v1|146502575203|0,original Rolex 2030 4424 GREAT WHEEL - NEW OLD...,80.00,6.00,86.00,USD,Rolex,2030,4424,New,None,Rolex_2030_4424_New_UNK,14027,99.9,3,2,US,2025-04-07T16:52:40.000Z
41,v1|327017503763|0,Brand New Factory Rolex Part Cal. 2030-4429 Es...,129.99,15.00,144.99,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,1202,99.8,0,3,US,2026-02-25T03:03:12.000Z
42,v1|276545997458|0,GENUINE Rolex 2030 2035 4416 Winding Bridge Pe...,60.00,0.00,60.00,USD,Rolex,2030,4416,Used,None,Rolex_2030_4416_Used_UNK,3692,100.0,0,2,US,2024-07-10T18:41:29.000Z
43,v1|226418950711|0,Genuine Rolex 2030-4458 Hour Wheel - New Facto...,69.95,0.00,69.95,USD,Rolex,2030,4458,New,None,Rolex_2030_4458_New_UNK,3603,99.8,1,2,US,2024-10-26T20:39:29.000Z
44,v1|126030520688|0,ROLEX CAL 2030 - 4429 ESCAPE WHEEL - EXHAUST W...,104.43,46.41,150.84,USD,Rolex,2030,4429,None,escape wheel,Rolex_2030_4429_UNK_escape wheel,430,100.0,0,1,IT,2023-07-27T16:28:30.000Z
45,v1|405076459132|0,Rolex 2030 #4425 Third Wheel Sealed New Authen...,65.00,0.00,65.00,USD,Rolex,2030,4425,New,third wheel,Rolex_2030_4425_New_third wheel,142414,99.8,0,1,US,2024-07-03T23:44:04.000Z
46,v1|277071657979|0,GENUINE Rolex 2030 2035 4415 Balance Bridge Co...,310.00,0.00,310.00,USD,Rolex,2030,4415,Used,None,Rolex_2030_4415_Used_UNK,3692,100.0,0,1,US,2025-04-28T16:00:05.000Z
47,v1|134441261086|0,Rolex 2030 4450 Setting Lever Jumper. Genuine ...,35.99,3.00,38.99,USD,Rolex,2030,4450,New,None,Rolex_2030_4450_New_UNK,21911,100.0,6,10,US,2023-02-07T20:35:38.000Z
48,v1|227210892570|0,Rolex 2030 4423 Used Good Condition Minute Pin...,88.89,55.00,143.89,USD,Rolex,2030,4423,Used,None,Rolex_2030_4423_Used_UNK,1330,100.0,0,5,IT,2026-02-10T05:51:16.000Z
49,v1|134441261090|0,Rolex 2030 6140 Lower Oscillating Weight Jewel...,63.99,3.00,66.99,USD,Rolex,2030,6140,New,None,Rolex_2030_6140_New_UNK,21911,100.0,1,3,US,2023-02-07T20:35:38.000Z

In [ ]:
df.groupby("synthetic_id").size().sort_values(ascending=False)

synthetic_id
Rolex_2030_4429_New_escape wheel      10
Rolex_2030_4425_New_third wheel        4
Rolex_2030_4429_Used_escape wheel      3
Rolex_2030_4422_New_barrel             3
Rolex_2030_4424_New_UNK                2
Rolex_2030_4426_New_UNK                2
Rolex_2030_4421_New_barrel             1
Rolex_2030_4415_Used_UNK               1
Rolex_2030_4423_Used_UNK               1
Rolex_2030_4416_Used_UNK               1
Rolex_2030_4421_New_UNK                1
Rolex_2030_4425_Used_third wheel       1
Rolex_2030_4429_UNK_escape wheel       1
Rolex_2030_4432_Used_balance wheel     1
Rolex_2030_4438_New_stem               1
Rolex_2030_4440_New_UNK                1
Rolex_2030_4442_Used_UNK               1
Rolex_2030_4450_New_UNK                1
Rolex_2030_4454_New_UNK                1
Rolex_2030_4458_New_Hour Wheel         1
Rolex_2030_4458_New_UNK                1
Rolex_2030_4472_Used_UNK               1
Rolex_2030_4474_New_rotor              1
Rolex_2030_4474_Used_UNK               1
Rolex_2030_4474_Used_rotor             1
Rolex_2030_4490_New_UNK                1
Rolex_2030_4493_New_UNK                1
Rolex_2030_6140_New_UNK                1
Rolex_2030_UNK_Used_UNK                1
Rolex_2035_4424_New_UNK                1
Rolex_2035_4425_New_third wheel        1
Rolex_2035_4429_New_escape wheel       1
dtype: int64

In [ ]:
df[df['synthetic_id'] == 'Rolex_2030_4429_New_escape wheel']

,item_id,title,price,shipping_cost,net_price,currency,brand,caliber,part_number,condition,component_type,synthetic_id,seller_score,seller_feedback_pct,sold_qty,remaining_qty,country,created_at
1,v1|263029195134|0,Brand New Factory Rolex Part Cal. 2030-4429 Es...,142.73,0.00,142.73,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,954,100.0,2,2,US,2017-06-09T19:35:55.000Z
4,v1|178028834648|0,Brand New Factory Rolex Part Cal. 2030-4429 Es...,120.00,0.00,120.00,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,6107,99.7,1,5,US,2026-04-07T00:48:57.000Z
6,v1|306354920959|0,ROLEX-ESCAPE WHEEL-FACTORY SEALED-CAL 2030 PAR...,108.00,0.00,108.00,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,1655,99.7,2,2,US,2025-06-16T19:29:32.000Z
7,v1|306049913094|0,"Rolex Original New 2030 2035, 4429 Escape Whee...",73.88,40.30,114.18,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,617,100.0,5,21,GB,2025-01-18T21:50:56.000Z
8,v1|306752648885|0,"Rolex Original New 2030 2035, 4429 Escape Whee...",76.95,40.25,117.20,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,617,100.0,2,21,GB,2026-02-05T21:34:18.000Z
12,v1|187840407423|0,ONE NEW Sealed Original Rolex part 2030-4429 E...,99.00,20.00,119.00,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,349,99.7,0,6,AE,2025-12-14T08:55:08.000Z
13,v1|227185022459|0,Rolex 2030 4429 New Blister X1 Piece Escape Wheel,186.79,55.00,241.79,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,1330,100.0,0,3,IT,2026-01-22T21:28:21.000Z
16,v1|358370765683|0,Genuine Rolex Escape Wheel Cal 2030/2035 Ladie...,175.00,10.00,185.00,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,3577,100.0,0,2,US,2026-03-24T19:50:29.000Z
28,v1|376090184590|0,Genuine Rolex 2030-4429 Escape Wheel Factory S...,137.50,11.03,148.53,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,47,100.0,0,1,CA,2025-03-22T17:16:48.000Z
41,v1|327017503763|0,Brand New Factory Rolex Part Cal. 2030-4429 Es...,129.99,15.00,144.99,USD,Rolex,2030,4429,New,escape wheel,Rolex_2030_4429_New_escape wheel,1202,99.8,0,3,US,2026-02-25T03:03:12.000Z

In [ ]:
final_data

[{'itemId': 'v1|256447115234|556586004259',
  'sellerItemRevision': '3',
  'title': 'Genuine ROLEX 2030 Watch Parts 4421 4422 4427 4429 4432 4439 4440 4441 4454 4478',
  'shortDescription': '4478 Spring Clip. Caliber 2030. Genuine ROLEX Parts. 4441 Crown Wheel. 4440 Sliding Pinion. 4439 Winding Pinion.',
  'price': {'value': '35.00', 'currency': 'USD'},
  'categoryPath': 'Jewelry & Watches|Watches, Parts & Accessories|Parts, Tools & Guides|Parts|Other Watch Parts',
  'categoryIdPath': '281|260324|173696|260327|10324',
  'condition': 'New with tags',
  'conditionId': '1000',
  'itemLocation': {'city': 'Cranford',
   'stateOrProvince': 'New Jersey',
   'postalCode': '070**',
   'country': 'US'},
  'image': {'imageUrl': 'https://i.ebayimg.com/images/g/7yAAAOSwcz5l9ItG/s-l1600.jpg',
   'width': 1600,
   'height': 1600},
  'additionalImages': [{'imageUrl': 'https://i.ebayimg.com/images/g/dWIAAOSw7Ztl9ItH/s-l1600.jpg',
    'width': 1600,
    'height': 1600}],
  'brand': 'Rolex',
  'itemCreationDate': '2024-03-15T17:56:52.000Z',
  'seller': {'username': 'cameragirl28',
   'feedbackPercentage': '99.3',
   'feedbackScore': 1809},
  'estimatedAvailabilities': [{'deliveryOptions': ['SHIP_TO_HOME'],
    'estimatedAvailabilityStatus': 'IN_STOCK',
    'estimatedAvailableQuantity': 1,
    'estimatedSoldQuantity': 1,
    'estimatedRemainingQuantity': 1}],
  'shippingOptions': [{'shippingServiceCode': 'USPS First Class',
    'trademarkSymbol': '®',
    'shippingCarrierCode': 'USPS',
    'type': 'Standard Shipping',
    'shippingCost': {'value': '0.00', 'currency': 'USD'},
    'quantityUsedForEstimate': 1,
    'minEstimatedDeliveryDate': '2026-05-28T10:00:00.000Z',
    'maxEstimatedDeliveryDate': '2026-06-02T10:00:00.000Z',
    'additionalShippingCostPerUnit': {'value': '0.00', 'currency': 'USD'},
    'shippingCostType': 'FIXED'}],
  'shipToLocations': {'regionIncluded': [{'regionName': 'United States',
     'regionType': 'COUNTRY',
     'regionId': 'US'},
    {'regionName': 'Denmark', 'regionType': 'COUNTRY', 'regionId': 'DK'},
    {'regionName': 'Guatemala', 'regionType': 'COUNTRY', 'regionId': 'GT'},
    {'regionName': 'New Zealand', 'regionType': 'COUNTRY', 'regionId': 'NZ'},
    {'regionName': 'Fiji', 'regionType': 'COUNTRY', 'regionId': 'FJ'},
    {'regionName': 'Papua New Guinea',
     'regionType': 'COUNTRY',
     'regionId': 'PG'},
    {'regionName': 'Solomon Islands',
     'regionType': 'COUNTRY',
     'regionId': 'SB'},
    {'regionName': 'Vatican City State',
     'regionType': 'COUNTRY',
     'regionId': 'VA'},
    {'regionName': 'Sierra Leone', 'regionType': 'COUNTRY', 'regionId': 'SL'},
    {'regionName': 'Nauru', 'regionType': 'COUNTRY', 'regionId': 'NR'},
    {'regionName': 'Wallis and Futuna',
     'regionType': 'COUNTRY',
     'regionId': 'WF'},
    {'regionName': 'Anguilla', 'regionType': 'COUNTRY', 'regionId': 'AI'},
    {'regionName': 'El Salvador', 'regionType': 'COUNTRY', 'regionId': 'SV'},
    {'regionName': 'Gambia', 'regionType': 'COUNTRY', 'regionId': 'GM'},
    {'regionName': 'Dominican Republic',
     'regionType': 'COUNTRY',
     'regionId': 'DO'},
    {'regionName': 'Malaysia', 'regionType': 'COUNTRY', 'regionId': 'MY'},
    {'regionName': 'Cameroon', 'regionType': 'COUNTRY', 'regionId': 'CM'},
    {'regionName': 'Guyana', 'regionType': 'COUNTRY', 'regionId': 'GY'},
    {'regionName': 'Taiwan', 'regionType': 'COUNTRY', 'regionId': 'TW'},
    {'regionName': 'Azerbaijan Republic',
     'regionType': 'COUNTRY',
     'regionId': 'AZ'},
    {'regionName': 'Poland', 'regionType': 'COUNTRY', 'regionId': 'PL'},
    {'regionName': 'Macau', 'regionType': 'COUNTRY', 'regionId': 'MO'},
    {'regionName': 'Georgia', 'regionType': 'COUNTRY', 'regionId': 'GE'},
    {'regionName': 'Suriname', 'regionType': 'COUNTRY', 'regionId': 'SR'},
    {'regionName': 'Tonga', 'regionType': 'COUNTRY', 'regionId': 'TO'},
    {'regionName': 'Kenya', 'regionType': 'COUNTRY', 'regionId': 'KE'},
    {'regionName': 'Argentina', 'regionType': 'COUNTRY', 'regionId': 'AR'},
    {'regionName': 'San Marino', 'regionType': 'COUNTRY', 'regionId': 'SM'},
    {'regionName': 'Guinea-Bissau', 'regionType': 'COUNTRY', 'regionId': 'GW'},
    {'regionName': 'Armenia', 'regionType': 'COUNTRY', 'regionId': 'AM'},
    {'regionName': 'Uzbekistan', 'regionType': 'COUNTRY', 'regionId': 'UZ'},
    {'regionName': 'Eritrea', 'regionType': 'COUNTRY', 'regionId': 'ER'},
    {'regionName': 'Senegal', 'regionType': 'COUNTRY', 'regionId': 'SN'},
    {'regionName': 'Togo', 'regionType': 'COUNTRY', 'regionId': 'TG'},
    {'regionName': 'Saint Kitts-Nevis',
     'regionType': 'COUNTRY',
     'regionId': 'KN'},
    {'regionName': 'Morocco', 'regionType': 'COUNTRY', 'regionId': 'MA'},
    {'regionName': 'Ireland', 'regionType': 'COUNTRY', 'regionId': 'IE'},
    {'regionName': 'Burundi', 'regionType': 'COUNTRY', 'regionId': 'BI'},
    {'regionName': 'Saint Vincent and the Grenadines',
     'regionType': 'COUNTRY',
     'regionId': 'VC'},
    {'regionName': 'Netherlands', 'regionType': 'COUNTRY', 'regionId': 'NL'},
    {'regionName': 'Slovakia', 'regionType': 'COUNTRY', 'regionId': 'SK'},
    {'regionName': 'Slovenia', 'regionType': 'COUNTRY', 'regionId': 'SI'},
    {'regionName': 'Equatorial Guinea',
     'regionType': 'COUNTRY',
     'regionId': 'GQ'},
    {'regionName': 'Thailand', 'regionType': 'COUNTRY', 'regionId': 'TH'},
    {'regionName': 'Mauritania', 'regionType': 'COUNTRY', 'regionId': 'MR'},
    {'regionName': 'Belize', 'regionType': 'COUNTRY', 'regionId': 'BZ'},
    {'regionName': 'Philippines', 'regionType': 'COUNTRY', 'regionId': 'PH'},
    {'regionName': 'Aruba', 'regionType': 'COUNTRY', 'regionId': 'AW'},
    {'regionName': 'Democratic Republic of the Congo',
     'regionType': 'COUNTRY',
     'regionId': 'CD'},
    {'regionType': 'COUNTRY', 'regionId': 'UY'},
    {'regionName': 'Republic of the Congo',
     'regionType': 'COUNTRY',
     'regionId': 'CG'},
    {'regionName': 'Sweden', 'regionType': 'COUNTRY', 'regionId': 'SE'},
    {'regionName': 'Colombia', 'regionType': 'COUNTRY', 'regionId': 'CO'},
    {'regionName': 'Iceland', 'regionType': 'COUNTRY', 'regionId': 'IS'},
    {'regionName': 'Spain', 'regionType': 'COUNTRY', 'regionId': 'ES'},
    {'regionName': 'Macedonia', 'regionType': 'COUNTRY', 'regionId': 'MK'},
    {'regionName': 'Estonia', 'regionType': 'COUNTRY', 'regionId': 'EE'},
    {'regionName': 'Belgium', 'regionType': 'COUNTRY', 'regionId': 'BE'},
    {'regionName': 'Liechtenstein', 'regionType': 'COUNTRY', 'regionId': 'LI'},
    {'regionName': 'Benin', 'regionType': 'COUNTRY', 'regionId': 'BJ'},
    {'regionName': 'Algeria', 'regionType': 'COUNTRY', 'regionId': 'DZ'},
    {'regionName': 'Bermuda', 'regionType': 'COUNTRY', 'regionId': 'BM'},
    {'regionName': 'Montserrat', 'regionType': 'COUNTRY', 'regionId': 'MS'},
    {'regionName': 'Zambia', 'regionType': 'COUNTRY', 'regionId': 'ZM'},
    {'regionName': 'South Korea', 'regionType': 'COUNTRY', 'regionId': 'KR'},
    {'regionName': 'Antigua and Barbuda',
     'regionType': 'COUNTRY',
     'regionId': 'AG'},
    {'regionName': 'Vanuatu', 'regionType': 'COUNTRY', 'regionId': 'VU'},
    {'regionName': 'Ecuador', 'regionType': 'COUNTRY', 'regionId': 'EC'},
    {'regionName': 'Albania', 'regionType': 'COUNTRY', 'regionId': 'AL'},
    {'regionName': 'Swaziland', 'regionType': 'COUNTRY', 'regionId': 'SZ'},
    {'regionName': 'Italy', 'regionType': 'COUNTRY', 'regionId': 'IT'},
    {'regionName': 'Ethiopia', 'regionType': 'COUNTRY', 'regionId': 'ET'},
    {'regionName': 'Monaco', 'regionType': 'COUNTRY', 'regionId': 'MC'},
    {'regionName': 'Niger', 'regionType': 'COUNTRY', 'regionId': 'NE'},
    {'regionName': 'Tanzania', 'regionType': 'COUNTRY', 'regionId': 'TZ'},
    {'regionName': 'Pakistan', 'regionType': 'COUNTRY', 'regionId': 'PK'},
    {'regionName': 'Burkina Faso', 'regionType': 'COUNTRY', 'regionId': 'BF'},
    {'regionName': 'Panama', 'regionType': 'COUNTRY', 'regionId': 'PA'},
    {'regionName': 'Singapore', 'regionType': 'COUNTRY', 'regionId': 'SG'},
    {'regionName': 'Kyrgyzstan', 'regionType': 'COUNTRY', 'regionId': 'KG'},
    {'regionName': 'Switzerland', 'regionType': 'COUNTRY', 'regionId': 'CH'},
    {'regionName': 'Ghana', 'regionType': 'COUNTRY', 'regionId': 'GH'},
    {'regionName': 'Djibouti', 'regionType': 'COUNTRY', 'regionId': 'DJ'},
    {'regionName': 'Puerto Rico', 'regionType': 'COUNTRY', 'regionId': 'PR'},
    {'regionName': 'Chile', 'regionType': 'COUNTRY', 'regionId': 'CL'},
    {'regionName': 'China', 'regionType': 'COUNTRY', 'regionId': 'CN'},
    {'regionName': 'Cape Verde Islands',
     'regionType': 'COUNTRY',
     'regionId': 'CV'},
    {'regionName': 'Moldova', 'regionType': 'COUNTRY', 'regionId': 'MD'},
    {'regionName': 'Mali', 'regionType': 'COUNTRY', 'regionId': 'ML'},
    {'regionName': 'Botswana', 'regionType': 'COUNTRY', 'regionId': 'BW'},
    {'regionName': 'Republic of Croatia',
     'regionType': 'COUNTRY',
     'regionId': 'HR'},
    {'regionName': 'Cambodia', 'regionType': 'COUNTRY', 'regionId': 'KH'},
    {'regionName': 'Madagascar', 'regionType': 'COUNTRY', 'regionId': 'MG'},
    {'regionName': 'Indonesia', 'regionType': 'COUNTRY', 'regionId': 'ID'},
    {'regionName': 'Portugal', 'regionType': 'COUNTRY', 'regionId': 'PT'},
    {'regionName': 'Tajikistan', 'regionType': 'COUNTRY', 'regionId': 'TJ'},
    {'regionName': 'Vietnam', 'regionType': 'COUNTRY', 'regionId': 'VN'},
    {'regionName': 'Malta', 'regionType': 'COUNTRY', 'regionId': 'MT'},
    {'regionName': 'Cayman Islands',
     'regionType': 'COUNTRY',
     'regionId': 'KY'},
    {'regionName': 'Paraguay', 'regionType': 'COUNTRY', 'regionId': 'PY'},
    {'regionName': 'Cyprus', 'regionType': 'COUNTRY', 'regionId': 'CY'},
    {'regionName': 'Seychelles', 'regionType': 'COUNTRY', 'regionId': 'SC'},
    {'regionName': 'Liberia', 'regionType': 'COUNTRY', 'regionId': 'LR'},
    {'regionName': 'Rwanda', 'regionType': 'COUNTRY', 'regionId': 'RW'},
    {'regionName': 'Bangladesh', 'regionType': 'COUNTRY', 'regionId': 'BD'},
    {'regionName': 'Bolivia', 'regionType': 'COUNTRY', 'regionId': 'BO'},
    {'regionName': 'Maldives', 'regionType': 'COUNTRY', 'regionId': 'MV'},
    {'regionName': 'Australia', 'regionType': 'COUNTRY', 'regionId': 'AU'},
    {'regionName': 'Austria', 'regionType': 'COUNTRY', 'regionId': 'AT'},
    {'regionName': 'Gibraltar', 'regionType': 'COUNTRY', 'regionId': 'GI'},
    {'regionName': 'Sri Lanka', 'regionType': 'COUNTRY', 'regionId': 'LK'},
    {'regionName': 'Hong Kong', 'regionType': 'COUNTRY', 'regionId': 'HK'},
    {'regionName': 'Central African Republic',
     'regionType': 'COUNTRY',
     'regionId': 'CF'},
    {'regionName': 'Gabon Republic',
     'regionType': 'COUNTRY',
     'regionId': 'GA'},
    {'regionName': 'Lesotho', 'regionType': 'COUNTRY', 'regionId': 'LS'},
    {'regionName': 'Nigeria', 'regionType': 'COUNTRY', 'regionId': 'NG'},
    {'regionName': 'Zimbabwe', 'regionType': 'COUNTRY', 'regionId': 'ZW'},
    {'regionName': 'Mauritius', 'regionType': 'COUNTRY', 'regionId': 'MU'},
    {'regionName': 'Saint Lucia', 'regionType': 'COUNTRY', 'regionId': 'LC'},
    {'regionName': 'Bulgaria', 'regionType': 'COUNTRY', 'regionId': 'BG'},
    {'regionName': 'Guinea', 'regionType': 'COUNTRY', 'regionId': 'GN'},
    {'regionName': 'Czech Republic',
     'regionType': 'COUNTRY',
     'regionId': 'CZ'},
    {'regionName': 'Norway', 'regionType': 'COUNTRY', 'regionId': 'NO'},
    {'regionName': 'Canada', 'regionType': 'COUNTRY', 'regionId': 'CA'},
    {'regionName': "Côte d'Ivoire (Ivory Coast)",
     'regionType': 'COUNTRY',
     'regionId': 'CI'},
    {'regionName': 'Turks and Caicos Islands',
     'regionType': 'COUNTRY',
     'regionId': 'TC'},
    {'regionName': 'Kiribati', 'regionType': 'COUNTRY', 'regionId': 'KI'},
    {'regionName': 'Andorra', 'regionType': 'COUNTRY', 'regionId': 'AD'},
    {'regionName': 'Grenada', 'regionType': 'COUNTRY', 'regionId': 'GD'},
    {'regionName': 'Greece', 'regionType': 'COUNTRY', 'regionId': 'GR'},
    {'regionName': 'Romania', 'regionType': 'COUNTRY', 'regionId': 'RO'},
    {'regionName': 'Costa Rica', 'regionType': 'COUNTRY', 'regionId': 'CR'},
    {'regionName': 'India', 'regionType': 'COUNTRY', 'regionId': 'IN'},
    {'regionName': 'Greenland', 'regionType': 'COUNTRY', 'regionId': 'GL'},
    {'regionName': 'Mexico', 'regionType': 'COUNTRY', 'regionId': 'MX'},
    {'regionName': 'Serbia', 'regionType': 'COUNTRY', 'regionId': 'RS'},
    {'regionName': 'Kazakhstan', 'regionType': 'COUNTRY', 'regionId': 'KZ'},
    {'regionName': 'Montenegro', 'regionType': 'COUNTRY', 'regionId': 'ME'},
    {'regionName': 'Japan', 'regionType': 'COUNTRY', 'regionId': 'JP'},
    {'regionName': 'Nepal', 'regionType': 'COUNTRY', 'regionId': 'NP'},
    {'regionName': 'Bahamas', 'regionType': 'COUNTRY', 'regionId': 'BS'},
    {'regionName': 'Lithuania', 'regionType': 'COUNTRY', 'regionId': 'LT'},
    {'regionName': 'Trinidad and Tobago',
     'regionType': 'COUNTRY',
     'regionId': 'TT'},
    {'regionName': 'United Kingdom',
     'regionType': 'COUNTRY',
     'regionId': 'GB'},
    {'regionName': 'Malawi', 'regionType': 'COUNTRY', 'regionId': 'MW'},
    {'regionName': 'Bosnia and Herzegovina',
     'regionType': 'COUNTRY',
     'regionId': 'BA'},
    {'regionName': 'Hungary', 'regionType': 'COUNTRY', 'regionId': 'HU'},
    {'regionName': 'Angola', 'regionType': 'COUNTRY', 'regionId': 'AO'},
    {'regionName': 'Nicaragua', 'regionType': 'COUNTRY', 'regionId': 'NI'},
    {'regionName': 'Finland', 'regionType': 'COUNTRY', 'regionId': 'FI'},
    {'regionName': 'Tunisia', 'regionType': 'COUNTRY', 'regionId': 'TN'},
    {'regionName': 'Uganda', 'regionType': 'COUNTRY', 'regionId': 'UG'},
    {'regionName': 'Luxembourg', 'regionType': 'COUNTRY', 'regionId': 'LU'},
    {'regionName': 'Brazil', 'regionType': 'COUNTRY', 'regionId': 'BR'},
    {'regionName': 'Turkey', 'regionType': 'COUNTRY', 'regionId': 'TR'},
    {'regionName': 'Western Samoa', 'regionType': 'COUNTRY', 'regionId': 'WS'},
    {'regionName': 'France', 'regionType': 'COUNTRY', 'regionId': 'FR'},
    {'regionName': 'Germany', 'regionType': 'COUNTRY', 'regionId': 'DE'},
    {'regionName': 'Egypt', 'regionType': 'COUNTRY', 'regionId': 'EG'},
    {'regionName': 'Latvia', 'regionType': 'COUNTRY', 'regionId': 'LV'},
    {'regionName': 'Jamaica', 'regionType': 'COUNTRY', 'regionId': 'JM'},
    {'regionName': 'Mozambique', 'regionType': 'COUNTRY', 'regionId': 'MZ'},
    {'regionName': 'Namibia', 'regionType': 'COUNTRY', 'regionId': 'NA'},
    {'regionName': 'Peru', 'regionType': 'COUNTRY', 'regionId': 'PE'},
    {'regionName': 'Honduras', 'regionType': 'COUNTRY', 'regionId': 'HN'}],
   'regionExcluded': [{'regionName': 'Alaska/Hawaii',
     'regionType': 'COUNTRY_REGION',
     'regionId': '_AH'},
    {'regionName': 'APO/FPO',
     'regionType': 'COUNTRY_REGION',
     'regionId': '_AP'},
    {'regionName': 'Saint Helena', 'regionType': 'COUNTRY', 'regionId': 'SH'},
    {'regionName': 'Libya', 'regionType': 'COUNTRY', 'regionId': 'LY'},
    {'regionName': 'Mayotte', 'regionType': 'COUNTRY', 'regionId': 'YT'},
    {'regionName': 'Chad', 'regionType': 'COUNTRY', 'regionId': 'TD'},
    {'regionName': 'Western Sahara',
     'regionType': 'COUNTRY',
     'regionId': 'EH'},
    {'regionName': 'Comoros', 'regionType': 'COUNTRY', 'regionId': 'KM'},
    {'regionName': 'Somalia', 'regionType': 'COUNTRY', 'regionId': 'SO'},
    {'regionName': 'South Africa', 'regionType': 'COUNTRY', 'regionId': 'ZA'},
    {'regionName': 'Afghanistan', 'regionType': 'COUNTRY', 'regionId': 'AF'},
    {'regionName': 'Mongolia', 'regionType': 'COUNTRY', 'regionId': 'MN'},
    {'regionName': 'Russian Federation',
     'regionType': 'COUNTRY',
     'regionId': 'RU'},
    {'regionName': 'Turkmenistan', 'regionType': 'COUNTRY', 'regionId': 'TM'},
    {'regionName': 'Bhutan', 'regionType': 'COUNTRY', 'regionId': 'BT'},
    {'regionName': 'Laos', 'regionType': 'COUNTRY', 'regionId': 'LA'},
    {'regionName': 'Brunei Darussalam',
     'regionType': 'COUNTRY',
     'regionId': 'BN'},
    {'regionName': 'Yemen', 'regionType': 'COUNTRY', 'regionId': 'YE'},
    {'regionName': 'Oman', 'regionType': 'COUNTRY', 'regionId': 'OM'},
    {'regionName': 'United Arab Emirates',
     'regionType': 'COUNTRY',
     'regionId': 'AE'},
    {'regionName': 'Qatar', 'regionType': 'COUNTRY', 'regionId': 'QA'},
    {'regionName': 'Saudi Arabia', 'regionType': 'COUNTRY', 'regionId': 'SA'},
    {'regionName': 'Iraq', 'regionType': 'COUNTRY', 'regionId': 'IQ'},
    {'regionName': 'Israel', 'regionType': 'COUNTRY', 'regionId': 'IL'},
    {'regionName': 'Kuwait', 'regionType': 'COUNTRY', 'regionId': 'KW'},
    {'regionName': 'Lebanon', 'regionType': 'COUNTRY', 'regionId': 'LB'},
    {'regionName': 'Jordan', 'regionType': 'COUNTRY', 'regionId': 'JO'},
    {'regionName': 'Bahrain', 'regionType': 'COUNTRY', 'regionId': 'BH'},
    {'regionName': 'Netherlands Antilles',
     'regionType': 'COUNTRY',
     'regionId': 'AN'},
    {'regionName': 'Guadeloupe', 'regionType': 'COUNTRY', 'regionId': 'GP'},
    {'regionName': 'Dominica', 'regionType': 'COUNTRY', 'regionId': 'DM'},
    {'regionName': 'British Virgin Islands',
     'regionType': 'COUNTRY',
     'regionId': 'VG'},
    {'regionName': 'Haiti', 'regionType': 'COUNTRY', 'regionId': 'HT'},
    {'regionName': 'Virgin Islands (U.S.)',
     'regionType': 'COUNTRY',
     'regionId': 'VI'},
    {'regionName': 'Belarus', 'regionType': 'COUNTRY', 'regionId': 'BY'},
    {'regionName': 'Svalbard and Jan Mayen',
     'regionType': 'COUNTRY',
     'regionId': 'SJ'},
    {'regionName': 'Guernsey', 'regionType': 'COUNTRY', 'regionId': 'GG'},
    {'regionName': 'Ukraine', 'regionType': 'COUNTRY', 'regionId': 'UA'},
    {'regionName': 'Jersey', 'regionType': 'COUNTRY', 'regionId': 'JE'},
    {'regionName': 'Saint Pierre and Miquelon',
     'regionType': 'COUNTRY',
     'regionId': 'PM'},
    {'regionName': 'Micronesia', 'regionType': 'COUNTRY', 'regionId': 'FM'},
    {'regionName': 'Marshall Islands',
     'regionType': 'COUNTRY',
     'regionId': 'MH'},
    {'regionName': 'Tuvalu', 'regionType': 'COUNTRY', 'regionId': 'TV'},
    {'regionName': 'Palau', 'regionType': 'COUNTRY', 'regionId': 'PW'},
    {'regionName': 'American Samoa',
     'regionType': 'COUNTRY',
     'regionId': 'AS'},
    {'regionName': 'Niue', 'regionType': 'COUNTRY', 'regionId': 'NU'},
    {'regionName': 'Cook Islands', 'regionType': 'COUNTRY', 'regionId': 'CK'},
    {'regionName': 'Guam', 'regionType': 'COUNTRY', 'regionId': 'GU'},
    {'regionName': 'Falkland Islands (Islas Malvinas)',
     'regionType': 'COUNTRY',
     'regionId': 'FK'},
    {'regionName': 'Venezuela', 'regionType': 'COUNTRY', 'regionId': 'VE'},
    {'regionName': 'French Polynesia',
     'regionType': 'COUNTRY',
     'regionId': 'PF'},
    {'regionName': 'New Caledonia', 'regionType': 'COUNTRY', 'regionId': 'NC'},
    {'regionName': 'Reunion', 'regionType': 'COUNTRY', 'regionId': 'RE'},
    {'regionName': 'Barbados', 'regionType': 'COUNTRY', 'regionId': 'BB'},
    {'regionName': 'Martinique', 'regionType': 'COUNTRY', 'regionId': 'MQ'},
    {'regionName': 'French Guiana',
     'regionType': 'COUNTRY',
     'regionId': 'GF'}]},
  'returnTerms': {'returnsAccepted': False},
  'taxes': [{'taxJurisdiction': {'region': {'regionName': 'Alabama',
      'regionType': 'STATE_OR_PROVINCE'},
     'taxJurisdictionId': 'AL'},
    'taxType': 'STATE_SALES_TAX',
    'shippingAndHandlingTaxed': True,
    'includedInPrice': False,
    'ebayCollectAndRemitTax': True},
   {'taxJurisdiction': {'region': {'regionName': 'Alaska',
      'regionType': 'STATE_OR_PROVINCE'},
     'taxJurisdictionId': 'AK'},
    'taxType': 'STATE_SALES_TAX',
    'shippingAndHandlingTaxed': True,
    'includedInPrice': False,
    'ebayCollectAndRemitTax': True},
   {'taxJurisdiction': {'region': {'regionName': 'Arizona',
      'regionType': 'STATE_OR_PROVINCE'},
     'taxJurisdictionId': 'AZ'},
    'taxType': 'STATE_SALES_TAX',